### ISSUE TITLE
atRule.raw.before is not a function - Tailwind CSS and PostCSS Debug

### ISSUE THREAD

**Issue by georanma** [andywer/postcss-debug#24]
Recently ran into this issue with the latest postcss, tailwinds css, and webpack.
```
TypeError: atRule.raw.before is not a function
    at /home/george/Work/georanma-blog/assets/index.css:34:1
    at /home/george/Work/georanma-blog/node_modules/tailwindcss/lib/lib/substituteTailwindAtRules.js:69:20
    at /home/george/Work/georanma-blog/node_modules/postcss-debug/node_modules/postcss/lib/container.js:310:16
    at /home/george/Work/georanma-blog/node_modules/postcss-debug/node_modules/postcss/lib/container.js:135:18
    at Root.each (/home/george/Work/georanma-blog/node_modules/postcss-debug/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/home/george/Work/georanma-blog/node_modules/postcss-debug/node_modules/postcss/lib/container.js:131:17)
    at Root.walkAtRules (/home/george/Work/georanma-blog/node_modules/postcss-debug/node_modules/postcss/lib/container.js:308:17)
    at /home/george/Work/georanma-blog/node_modules/tailwindcss/lib/lib/substituteTailwindAtRules.js:51:9
    at LazyResult.run (/home/george/Work/georanma-blog/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/home/george/Work/georanma-blog/node_modules/postcss/lib/lazy-result.js:208:26)
    at /home/george/Work/georanma-blog/node_modules/postcss/lib/lazy-result.js:250:14
```
I was able to resolve the issue by forking the repo and updating the PostCSS dependancy. The library is using it's own version of PostCSS, `^5.0.19`, which installs `5.2.18` as is. 

@andywer Im guessing this is mostly abandoned? I was trying to debug my tailwind set up with regards to PostCSS Font Magician, and local fonts, but loading up all that CSS in the browser for a few steps seems to drag Firefox to a halt, so Id need to look for a different way to debug anyways.

**Comment by andywer** [comment]
Hey @georanma. Yeah, there is not much going on in this repo. If it's a relatively simple change to upgrade to the latest PostCSS version, I am happy to merge a PR.
